### PR TITLE
FShell w2t: Memory safety and overflow validation

### PR DESCRIPTION
**Pull request by tautschnig**

### CODE REVIEW

**Comment by tautschnig** [comment]
Thanks a lot for the immediate merge! Is there any chance of seeing the sv-comp18 tag move such that this could be included?

**Comment by dbeyer** [comment]
Waiting for permission from Tomas.

**Comment by dbeyer** [comment]
Chair said No.  So we will work with the benchmark definition with the tag 'svcomp18'.

**Comment by dbeyer** [comment]
Chair approved it. Moved tag.

**Pull request merged**
